[package]
name = "rCC"
version = "0.1.0"
authors = ["Nau Sakaguchi <nau.sakaguchi@sjsu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
